Dev overfore dager (#15)
* Ny søknad - overføring av dager
Tilpasset for ny søknad
La til nye topics
La til ny PDF template
Startet på tester.

* Ny JournalfortOverforeDager
Første fungerende test for ny søknad

* Ignore test

* Fjerner ubrukt meteic, og legger på todo

* Rettelse

* Tilpasser generert pdf til ny søknad og la til inline partial for søknad

* Parmteriserer testProducerProperties

* Kommenterer ut del av kode som foresaker følgende feil:
Feil ved 'PreprosesseringV1OverforeDager'. NoClassDefFoundError med melding 'Could not initialize class no.nav.helse.prosessering.v1.PreprossesertMeldingV1OverforeDagerMetricsKt'

* Tilpasset slik at ny søknad blir sendt til riktig endepunkt i K9-joark

* Ny søknad - overføring av dager
Tilpasset for ny søknad
La til nye topics
La til ny PDF template
Startet på tester.

* Ny JournalfortOverforeDager
Første fungerende test for ny søknad

* Ignore test

* Fjerner ubrukt meteic, og legger på todo

* Rettelse

* Tilpasser generert pdf til ny søknad og la til inline partial for søknad

* Parmteriserer testProducerProperties

* Kommenterer ut del av kode som foresaker følgende feil:
Feil ved 'PreprosesseringV1OverforeDager'. NoClassDefFoundError med melding 'Could not initialize class no.nav.helse.prosessering.v1.PreprossesertMeldingV1OverforeDagerMetricsKt'

* Tilpasset slik at ny søknad blir sendt til riktig endepunkt i K9-joark

* Trigger for deploy

* Trigger for deploy

* Fjerner feltet harSamfunnskritiskJobb og oppdaterer tester iht det

* Gjør antallDager og mottaker optional foreløpig

* Spesifisere logg for overføring av dager

* Gjør PDF mer lesbar

* La til fnrMottaker og oppdaterte tester og pdf til det

* La til antallBarn og oppdaterte tester og pdf til det

* Fikset reportMetrics slik at overfore dageer.reportMetrics fungerer

* Fikset pdf for barn og la til ny helper for handlebars

* Oppdaterte avhengigheter

* Kafka update

* Seneste dusseldorf-version håndterer thumbprint av cert.

* Legger til søknad på rett format etter journalføring

Tester format som blir lagt på kø både ved Utvidet antall dager og overføring av dager

* fnrMottaker required & legger til mottaker i melding etter journalført

* Fjerner optional for antallDager

* k9-format som støtter å ta inn liste med barn

* Legger til fosterbarn og format test for overføring av dager

* La til ny metric for antall dager

* Fjerner antallBarn fra søknaden og pdf

* Tilpasse til k9barn for fosterbarn

* Oppdaterer pdf med nytt format for fosterbarn

* Bedre loggmeldinger tilpasset overføre dager

* Bedre loggmelding og tilpassing etter oppgradering av gradle

Co-authored-by: Ramin Esfandiari <ramin_esfandiari_93@hotmail.com>
Co-authored-by: Erik Maximilian Forsman <Erik.Maximilian.Forsman@nav.no>